id: A55CE84E0
title: Prayer to Orgyen Jigme Chökyi Wangpo
type: translation
pechas:
- I7621A32D
- I191D6C8A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:41.460352
  last_modified_at: 2023-01-04 12:01:41.460366
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I7621A32D/A54D: D08F
  I191D6C8A/938A: D08F
